export { AccumulatorIcon } from './AccumulatorIcon'
export { AchivmentIcon } from './AchivmentIcon'
export { ArrowRightIcon } from './ArrowRightIcon'
export { CartActiveIcon, CartIcon } from './CartIcon'
export { CatalogIcon } from './CatalogIcon'
export { CircleIcon } from './CircleIcon'
export { DeliveryTruckIcon } from './DeliveryTruckIcon'
export { FeedBackIcon } from './FeedbackIcon'
export { HeartActiveIcon, HeartIcon } from './HeartIcon'
export { HomeIcon } from './HomeIcon'
export { InfoIcon } from './InfoIcon'
export { LightningIcon } from './LightningIcon'
export { Logo } from './Logo'
export { MarkedPlacementIcon } from './MarkedPlacementIcon'
export { PercentIcon } from './PercentIcon'
export { ScalesIcon } from './ScalesIcon'
export { ShareIcon } from './ShareIcon'
export { SpeedometerIcon } from './SpeedometerIcon'
export { StarIcon } from './StarIcon'
export { TimerIcon } from './TimerIcon'
export { TrashIcon } from './TrashIcon'
export { WalletIcon } from './WalletIcon'

export { GoogleMailIcon } from './mails/GoogleMailIcon'
export { OutlookMailIcon } from './mails/OutlookMailIcon'
export { YahooMailIcon } from './mails/YahooMailIcon'
export { YandexMailIcon } from './mails/YandexMailIcon'
