export { CartPage } from './CartPage/CartPage'
export { CatalogPage } from './CatalogPage/CatalogPage'
export { Layout } from './Layout/Layout'
export { MainPage } from './MainPage/MainPage'
export { NotFoundPage } from './NotFoundPage/NotFoundPage'
export { OrderPage } from './OrderPage/OrderPage'
export { OrderSuccessPage } from './OrderSuccessPage/OrderSuccessPage'
export { ProductPage } from './ProductPage/ProductPage'
