export { CartLayout } from './CartLayout/CartLayout'
export { CatalogProductsLayout } from './CatalogProductsLayout/CatalogProductsLayout'
export { CategoriesLayout } from './CategoriesLayout/CategoriesLayout'
export { FooterLayout } from './FooterLayout/FooterLayout'
export { HeaderLayout } from './HeaderLayout/HeaderLayout'
export { HeroLayout } from './HeroLayout/HeroLayout'
export { ProductsLayout } from './ProductsLayout/ProductsLayout'
export { ServiceLayout } from './ServiceLayout/ServiceLayout'
